"frontend":
  - "frontend/**"

"backend":
  - "backend/**"

"documentation":
  - "documentation/**"

"backend/deps":
  - "backend/Pipfile*"
  
"backend/routes":
  - "backend/src/routes/**"
  
"backend/models":
  - "backend/src/models.py"

"frontend/deps":
  - "frontend/package*.json"

"github":
  - ".github/**"

"github-actions":
  - ".github/workflows/*.yml"

"top-level":
  - "*"
  - ".*"
