"""empty message

Revision ID: f1feaa9a5e71
Revises: 
Create Date: 2023-03-24 16:28:24.246644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1feaa9a5e71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('choices', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('answer', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('emailverificationtokenss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_emailverificationtokenss_users_id_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('userpasswords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sa.LargeBinary(length=97), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_userpasswords_users_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usertokenss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_usertokenss_users_id_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usertokenss')
    op.drop_table('userpasswords')
    op.drop_table('emailverificationtokenss')
    op.drop_table('users')
    op.drop_table('questions')
    # ### end Alembic commands ###
