"""empty message

Revision ID: 913b3c2f883b
Revises: f1feaa9a5e71
Create Date: 2023-03-24 17:23:30.720278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913b3c2f883b'
down_revision = 'f1feaa9a5e71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlogs',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('causing_user', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_data', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['causing_user'], ['users.id'], name='fk_auditlogs_users_id_causing_user'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('signinauditlogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_signinauditlogs_users_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('emailverificationtokenss', sa.Column('created_on', sa.DateTime(timezone=True), nullable=False))
    op.add_column('questions', sa.Column('created_on', sa.DateTime(timezone=True), nullable=False))
    op.add_column('questions', sa.Column('creator', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_questions_users_id_creator', 'questions', 'users', ['creator'], ['id'])
    op.add_column('users', sa.Column('created_on', sa.DateTime(timezone=True), nullable=False))
    op.add_column('usertokenss', sa.Column('created_on', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usertokenss', 'created_on')
    op.drop_column('users', 'created_on')
    op.drop_constraint('fk_questions_users_id_creator', 'questions', type_='foreignkey')
    op.drop_column('questions', 'creator')
    op.drop_column('questions', 'created_on')
    op.drop_column('emailverificationtokenss', 'created_on')
    op.drop_table('signinauditlogs')
    op.drop_table('auditlogs')
    # ### end Alembic commands ###
